import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Play With Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>

      <main className={styles.main}>
        <a href='wallet'><h1><em>ENTER</em></h1></a>
        
      </main>

      <footer className={styles.footer}>
        <a>
        © Copyright 2022 CoolStudio 💋   with full of love 
          <span className={styles.logo}>
            
          </span>
        </a>
      </footer>
    </div>
  )
}
